#! /bin/sh
# ~/.config/bspwm/bspwmrc

# shortcut keys
# ~/.config/sxhkd/sxhkdrc

# Round corners and other aesthetics
# ~/.config/picom/picom.conf

# Article followed for hybrid setup w/ XFCE: https://github.com/bgdawes/bspwm-xfce-dotfiles/wiki

bash ~/.config/BigBagKbdTrixXKB/setxkb.sh 4ca us us

sxhkd &
[ ! -s ~/.config/mpd/pid ] && mpd

. "${HOME}/.config/bspwm/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config normal_border_color "$color16"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color16"

bspc config border_width 3
bspc config window_gap 0

bspc config top_padding 27
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.5b
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config click_to_focus any

bspc config pointer_modifier mod4
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 moveasd

#################
## Window rules ##
##################
# Deletes all rules
#bspc rule -r "*"

### App-specific stats
bspc rule -a Gpick state=floating
bspc rule -a File-roller state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Ristretto state=floating
bspc rule -a back-alacritty layer='below' state='fullscreen'

bspc rule -a \* node=focused
bspc rule -a xfce4-popup-whiskermenu state=floating border=off layer=normal
bspc rule -a Yad state=floating border=off layer=normal
bspc rule -a xfce4-notes floating=on

### Launch apps on specific workspaces

## Workspace 1 (Chat)
bspc rule -a discord desktop='^1'
bspc rule -a slack desktop='^1'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating

## Workspace 2 (Web Browser)
bspc rule -a brave-browser desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a libreWolf desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a freeTube desktop='^2' follow=on focus=on

## Workspace 3 and 4 (Terminal)
bspc rule -a alacritty desktop='^3' follow=on focus=on
bspc rule -a alacritty desktop='^4' follow=on focus=on

## Workspace 5 (Social)
bspc rule -a telegram-desktop desktop='^4' follow=on focus=on
bspc rule -a signal-desktop desktop='^4' follow=on focus=on
bspc rule -a zoom desktop='^4' follow=on focus=on

## Workspace 6 (Files)
bspc rule -a thunar desktop='^6' follow=on focus=on state=floating
bspc rule -a dolphin desktop='^6' follow=on focus=on state=floating
bspc rule -a transmission-gtk desktop='^6' follow=on focus=on
bspc rule -a deluge desktop='^6' follow=on focus=on

## Workspace 7 (Office)
# Email
bspc rule -a gimp desktop='^7' follow=on focus=on
bspc rule -a geary desktop='^7' follow=on focus=on

# FreeOffice suite
bspc rule -a tm desktop='^7' follow=on focus=on
bspc rule -a pm desktop='^7' follow=on focus=on
bspc rule -a pr desktop='^7' follow=on focus=on

# LibreOffice
bspc rule -a libreoffice-startcenter desktop='^7' follow=on focus=on

# Anki
bspc rule -a anki desktop='^7' follow=on focus=on state=floating

## Workspace 7 (Multimedia)
#bspc rule -a vlc desktop='^7' follow=on focus=on state=fullscreen
#bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
#bspc rule -a Audacity desktop='^7' follow=on focus=on

## Workspace 8 (Settings)
bspc rule -a Xfce4-settings-editor desktop='^8' follow=on focus=on state=floating
bspc rule -a Xfce4-settings-manager desktop='^8' follow=on focus=on state=floating


