game:
  exe: /home/narayana/Games/Warcraft_3_TFT/war3.exe
  working_dir: ~/Games/Warcraft_3_TFT
system: {}
wine:
  Desktop: false
  WineDesktop: 1920x1080
  fsync: true
  version: lutris-GE-Proton8-13-x86_64
